config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    devise_for :admin, controllers: {
      sessions: 'admin/sessions'
    }

    root to: 'homes#top'
    resources :genres, only: [:index, :create, :edit, :update]
    resources :games, only: [:new, :index, :create, :show, :edit, :update]
    resources :reviews, only: [:index, :show, :update, :edit, :create, :destroy]
    resources :users, only: [:index, :show, :edit, :update, :destroy]
  end

  scope module: :public do
    devise_for :users, controllers: {
      registrations: 'public/registrations',
      sessions: 'public/sessions'
    }

    root 'homes#top'
    get 'homes/about' => 'homes#about', as: 'about'
    get 'users/mypage' => 'users#show'

    resources :games, only: [:index, :show] do
      resources :reviews, only: [:index, :show, :edit, :create, :destroy]
      resources :favorites, only: [:create, :destroy]
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
end

app/models/game.rb
class Game < ApplicationRecord
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/games_controller.rb
class Admin::GamesController < ApplicationController
  def index
    @games = Game.all
    @game = Game.new
    @btntxt = "新規登録"
  end

  def show
    @game = Game.find(params[:id])
    # @game_reviews = @game.reviews
    @game_review = Review.new
  end

  def edit
    @game = Game.find(params[:id])
    @btntext = "更新"
  end

  def new
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      flash[:notice] = "新規登録が完了しました"
      redirect_to admin_game_path(@game.id)
    else
      flash.now[:alert] = "新規登録に失敗しました"
      render :new
    end
  end

  def update
    @game = Game.find(params[:id])
    if @game.update(game_params)
      flash[:notice] = "更新が完了しました"
      redirect_to admin_game_path(@game.id)
    else
      flash.now[:alert] = "更新に失敗しました"
      render :edit
    end
  end

  def destroy
    @game = Game.find(params[:id])
    if @game.destroy
      flash[:notice] = "ゲームを削除しました"
      redirect_to admin_games_path
    else
      flash.now[:alert] = "削除に失敗しました"
      render :index
    end
  end


  private

  def game_params
    params.require(:game).permit(:title, :body, :price, :genre_id)
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
    @btntxt = "新規登録"
  end

  def edit
    @genre = Genre.find(params[:id])
    @genres = Genre.all
    @btntxt = "更新"
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:notice] = "新規登録が完了しました"
      redirect_to admin_genres_path
    else
      flash.now[:alert] = "新規登録に失敗しました"
      render :index
    end
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:notice] = "更新が完了しました"
      redirect_to admin_genres_path
    else
      flash.now[:alert] = "更新に失敗しました"
      render :edit
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/games_helper.rb
module Admin::GamesHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
    <div class="container-fluid pt-5 bg-dark min-vh-10">
      <div class="row">

      </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">

      <div class="row justify-content-start">
        <a class="navbar-brand" href="/">
          <%= link_to 'Geek Reccomended Games','/' %>
        </a>
      </div>

      <div class = "row">
        <div class="col-lg-12">
          <div class="row justify-content-end mr-2">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          </div>
          <div class="row  justify-content-end mr-2 collapse navbar-collapse justify-content-lg-end" id="navbarNavDropdown">
            <ul class="navbar-nav d-flex flex-lg-row flex-wrap">
              <% if admin_admin_signed_in? %>
                <li>
                  <%= link_to admin_games_path, class: 'btn btn-outline-secondary mx-1 my-1' do %>
                    <i class="fa-solid fa-cake-candles"></i> ゲーム一覧
                  <% end %>
                </li>
                <li>
                  <%= link_to admin_users_path, class: 'btn btn-outline-secondary mx-1 my-1' do %>
                    <i class="fa-solid fa-users"></i> 会員一覧
                  <% end %>
                </li>
                <li>
                  <%= link_to admin_reviews_path, class: 'btn btn-outline-secondary mx-1 my-1' do %>
                    <i class="fa-solid fa-barcode"></i> レビュー一覧
                  <% end %>
                  </li>
                <li>
                  <%= link_to admin_genres_path, class: 'btn btn-outline-secondary mx-1 my-1' do %>
                    <i class="fa-solid fa-shapes"></i> ジャンル一覧
                  <% end %>
                </li>
                <li>
                <%= button_to destroy_admin_admin_session_path, method: :delete, class: 'btn btn-outline-secondary mx-1 my-1' do %>
                  <i class="fa-solid fa-right-from-bracket"></i> 管理者ログアウト
                <% end %>

                </li>
              <% elsif user_signed_in? %>
                <li>
                  <%= link_to users_mypage_path, class: 'btn btn-outline-secondary mx-1 my-1' do %>
                    <i class="fa-solid fa-user"></i> マイページ
                  <% end %>
                </li>
                <li>
                  <%= link_to games_path, class: 'btn btn-outline-secondary mx-1 my-1' do %>
                    <i class="fa-solid fa-cake-candles"></i> ゲーム一覧
                  <% end %>
                </li>
                <li>
                  <%= button_to destroy_user_session_path, method: :delete, class: 'btn btn-outline-secondary mx-1 my-1' do %>
                    <i class="fa-solid fa-right-from-bracket"></i> 会員ログアウト
                  <% end %>
                </li>
              <% else %>
                <li>
                  <%= link_to about_path, class: 'btn btn-outline-secondary mx-1 my-1' do %>
                    <i class="fa-solid fa-house">About</i>
                  <% end %>
                <li>
                  <%= link_to games_path, class: 'btn btn-outline-secondary mx-1 my-1' do %>
                    <i class="fa-solid fa-cake-candles"></i> ゲーム一覧
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_registration_path, class: 'btn btn-outline-secondary mx-1 my-1' do %>
                    <i class="fa-solid fa-user-plus"></i> 新規登録
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_session_path, class: 'btn btn-outline-secondary mx-1 my-1' do %>
                    <i class="fa-solid fa-right-to-bracket"></i> 会員ログイン
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
          </div>
        </div>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GRG</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/cad58204f4.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <div class="flash-message <%= message_type %>"><%= message %></div>
    <% end %>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>